import authenticate from "./authenticate.js";
import dashboard from "./dashboard.js";
import anonymous from "./anonymous.js";
import user from "./user.js";
import role from "./role.js";
import resource from "./resource.js";
import policy from "./policy.js";
import module from "./module.js";
import supplier from "./supplier.js";
import club from "./club.js";
import menu from "./menu.js";
import markup from "./markup.js";
import benefit from "./benefit.js";
import language from "./language.js";
import orderreport from "./orderreport.js";
import tier from "./tier.js";
import members from "./member.js";
import helper from "./helper.js";
import order from "./order.js";
import orders from "./orders.js";
import program from "./program.js";
import splash from "./splash.js";
import memberreport from "./memberreport.js";
import smtp from "./smtp.js"
import template from "./template.js";
import lists from "./lists.js";
import data from "./data.js";
import config from "./config.js";
import demo from "./demo.js";

import page from "./page.js";
import club_module from "./club_module.js";
import policyowners from "./policyowners.js";
import club_language from "./club_language.js";
import clubcurrency from "./clubcurrency.js";

import country from "./country.js";
import referral from "./referral.js";
import trip_coins from "./trip_coin.js";
import setting from "./setting.js";
import section from "./section.js";
export default (app) => {
    app.use(module);
    app.use(authenticate);
    app.use(dashboard);
    app.use(anonymous);
    app.use(user);
    app.use(role);
    app.use(resource);
    app.use(policy);
    app.use(module);
    app.use(supplier);
    app.use(club);
    app.use(menu);
    app.use(markup);
    app.use(benefit);
    app.use(language);
    app.use(orderreport);
    app.use(tier);
    app.use(members);
    app.use(helper);
    app.use(order);
    app.use(program);
    app.use(splash);
    app.use(memberreport);
    app.use(smtp);
    app.use(template);
    app.use(lists);
    app.use(data);
    app.use(config);
    app.use(page);
    app.use(club_module);
    app.use(policyowners);
    app.use(club_language);
    app.use(clubcurrency);
    app.use(demo);
    app.use(country);
    app.use(referral);
    app.use(trip_coins);
    app.use(setting);
    app.use(section);
    app.use(orders);
};